const outcomes = {
    // --- ROCK ---
    "rock_paper": "paper|covers",
    "rock_scissors": "rock|crushes",
    "rock_water": "water|erodes",
    "rock_fire": "rock|smothers",
    "rock_human": "rock|concussions",
    "rock_nuke": "nuke|vaporizes",
    "rock_cockroach": "rock|squashes",
    "rock_lawyer": "rock|silences",
    "rock_god": "god|created",
    "rock_atheist": "rock|is real",
    "rock_bitcoin": "rock|is tangible",
    "rock_alien": "alien|vaporizes",
    "rock_sponge": "rock|squashes",
    "rock_dragon": "dragon|eats",
    "rock_gun": "rock|jams",
    "rock_wall": "wall|stops",
    "rock_computer": "rock|smashes",
    "rock_money": "rock|crushes",
    "rock_camera": "rock|shatters",
    "rock_sun": "sun|melts",
    "rock_vampire": "rock|dusts",
    "rock_internet": "rock|disconnects",
    "rock_time": "time|erodes",
    "rock_cow": "rock|trips",

    // --- PAPER ---
    "paper_scissors": "scissors|cuts",
    "paper_water": "water|soaks",
    "paper_fire": "fire|burns",
    "paper_human": "human|tears",
    "paper_nuke": "nuke|incinerates",
    "paper_cockroach": "cockroach|eats",
    "paper_lawyer": "lawyer|files",
    "paper_god": "god|created trees",
    "paper_atheist": "paper|gives papercut",
    "paper_bitcoin": "bitcoin|replaces",
    "paper_alien": "alien|decodes",
    "paper_sponge": "sponge|wipes",
    "paper_dragon": "dragon|burns",
    "paper_gun": "gun|shoots through",
    "paper_wall": "paper|flyers over",
    "paper_computer": "computer|digitizes",
    "paper_money": "money|is made of",
    "paper_camera": "camera|photographs",
    "paper_sun": "sun|burns",
    "paper_vampire": "vampire|tears",
    "paper_internet": "internet|archives",
    "paper_time": "time|yellows",
    "paper_cow": "cow|eats",

    // --- SCISSORS ---
    "scissors_water": "water|rusts",
    "scissors_fire": "fire|melts",
    "scissors_human": "scissors|stabs",
    "scissors_nuke": "nuke|melts",
    "scissors_cockroach": "scissors|decapitates",
    "scissors_lawyer": "scissors|cuts red tape",
    "scissors_god": "god|unmakes",
    "scissors_atheist": "scissors|stabs",
    "scissors_bitcoin": "bitcoin|cannot cut",
    "scissors_alien": "alien|melts",
    "scissors_sponge": "scissors|cuts up",
    "scissors_dragon": "dragon|melts",
    "scissors_gun": "gun|shoots",
    "scissors_wall": "wall|smashes",
    "scissors_computer": "computer|hacks", // physical hack
    "scissors_money": "scissors|shreds",
    "scissors_camera": "camera|films",
    "scissors_sun": "sun|melts",
    "scissors_vampire": "vampire|breaks",
    "scissors_internet": "internet|disconnects",
    "scissors_time": "time|rusts",
    "scissors_cow": "cow|steps on",

    // --- WATER ---
    "water_fire": "water|extinguishes",
    "water_human": "human|drinks",
    "water_nuke": "nuke|boils",
    "water_cockroach": "cockroach|swims",
    "water_lawyer": "water|ruins suit",
    "water_god": "god|parts",
    "water_atheist": "atheist|evolved from",
    "water_bitcoin": "bitcoin|sinks", // mining rig
    "water_alien": "water|melts (Signs style)",
    "water_sponge": "sponge|absorbs",
    "water_dragon": "dragon|boils",
    "water_gun": "water|rusts",
    "water_wall": "wall|dams",
    "water_computer": "water|short circuits",
    "water_money": "money|launders",
    "water_camera": "water|ruins",
    "water_sun": "sun|evaporates",
    "water_vampire": "water|burns (if holy)",
    "water_internet": "water|floods servers",
    "water_time": "time|evaporates",
    "water_cow": "cow|drinks",

    // --- FIRE ---
    "fire_human": "fire|burns",
    "fire_nuke": "nuke|out-blasts",
    "fire_cockroach": "fire|roasts",
    "fire_lawyer": "fire|sends to hell",
    "fire_god": "god|created",
    "fire_atheist": "fire|burns",
    "fire_bitcoin": "bitcoin|burns drive",
    "fire_alien": "fire|scares",
    "fire_sponge": "fire|burns",
    "fire_dragon": "dragon|breathes",
    "fire_gun": "gun|melts",
    "fire_wall": "wall|stops",
    "fire_computer": "fire|melts",
    "fire_money": "fire|incinerates",
    "fire_camera": "camera|films",
    "fire_sun": "sun|is hotter",
    "fire_vampire": "fire|turns to ash",
    "fire_internet": "fire|trolls",
    "fire_time": "time|extinguishes",
    "fire_cow": "fire|cooks",

    // --- HUMAN ---
    "human_nuke": "nuke|vaporizes",
    "human_cockroach": "human|steps on",
    "human_lawyer": "lawyer|sues",
    "human_god": "god|judges",
    "human_atheist": "human|is",
    "human_bitcoin": "human|buys",
    "human_alien": "alien|abducts",
    "human_sponge": "human|squeezes",
    "human_dragon": "dragon|eats",
    "human_gun": "gun|shoots",
    "human_wall": "human|builds",
    "human_computer": "human|programs",
    "human_money": "human|craves",
    "human_camera": "camera|captures",
    "human_sun": "sun|burns",
    "human_vampire": "vampire|bites",
    "human_internet": "internet|addicts",
    "human_time": "time|ages",
    "human_cow": "human|eats burger",

    // --- NUKE ---
    "nuke_cockroach": "cockroach|survives",
    "nuke_lawyer": "nuke|vaporizes",
    "nuke_god": "god|dismantles",
    "nuke_atheist": "nuke|vaporizes",
    "nuke_bitcoin": "nuke|destroys grid",
    "nuke_alien": "nuke|blasts",
    "nuke_sponge": "nuke|vaporizes",
    "nuke_dragon": "nuke|obliterates",
    "nuke_gun": "nuke|melts",
    "nuke_wall": "nuke|levels",
    "nuke_computer": "computer|hacks", // WarGames logic
    "nuke_money": "nuke|makes worthless",
    "nuke_camera": "camera|films explosion",
    "nuke_sun": "sun|is bigger nuke",
    "nuke_vampire": "nuke|vaporizes",
    "nuke_internet": "nuke|disconnects",
    "nuke_time": "time|heals radiation",
    "nuke_cow": "nuke|cooks",

    // --- COCKROACH ---
    "cockroach_lawyer": "lawyer|is related",
    "cockroach_god": "god|created",
    "cockroach_atheist": "cockroach|disgusts",
    "cockroach_bitcoin": "cockroach|ignores",
    "cockroach_alien": "alien|eats",
    "cockroach_sponge": "cockroach|hides under",
    "cockroach_dragon": "dragon|ignores",
    "cockroach_gun": "gun|misses",
    "cockroach_wall": "cockroach|climbs",
    "cockroach_computer": "cockroach|bugs",
    "cockroach_money": "cockroach|poops on",
    "cockroach_camera": "camera|films",
    "cockroach_sun": "cockroach|hides from",
    "cockroach_vampire": "vampire|drinks",
    "cockroach_internet": "internet|ignores",
    "cockroach_time": "cockroach|outlives",
    "cockroach_cow": "cow|steps on",

    // --- LAWYER ---
    "lawyer_god": "lawyer|finds loophole",
    "lawyer_atheist": "lawyer|argues with",
    "lawyer_bitcoin": "lawyer|regulates",
    "lawyer_alien": "lawyer|sues for invasion",
    "lawyer_sponge": "lawyer|wipes evidence",
    "lawyer_dragon": "dragon|eats",
    "lawyer_gun": "lawyer|bans",
    "lawyer_wall": "lawyer|files injunction",
    "lawyer_computer": "computer|automates",
    "lawyer_money": "lawyer|takes 40%",
    "lawyer_camera": "camera|catches in 4k",
    "lawyer_sun": "sun|burns",
    "lawyer_vampire": "lawyer|represents",
    "lawyer_internet": "internet|doxxes",
    "lawyer_time": "time|bills hourly",
    "lawyer_cow": "lawyer|milks dry",

    // --- GOD ---
    "god_atheist": "atheist|disbelieves",
    "god_bitcoin": "god|is eternal",
    "god_alien": "god|created",
    "god_sponge": "god|created",
    "god_dragon": "god|smites",
    "god_gun": "god|jams",
    "god_wall": "god|crumbles",
    "god_computer": "god|crashes",
    "god_money": "money|is false idol",
    "god_camera": "camera|cannot capture",
    "god_sun": "god|created",
    "god_vampire": "god|damns",
    "god_internet": "internet|mocks",
    "god_time": "god|is timeless",
    "god_cow": "cow|is holy",

    // --- ATHEIST ---
    "atheist_bitcoin": "bitcoin|is new religion",
    "atheist_alien": "alien|proves life",
    "atheist_sponge": "atheist|uses",
    "atheist_dragon": "atheist|debunks",
    "atheist_gun": "gun|shoots",
    "atheist_wall": "wall|blocks",
    "atheist_computer": "computer|is logic",
    "atheist_money": "money|buys happiness",
    "atheist_camera": "camera|proves",
    "atheist_sun": "sun|is star",
    "atheist_vampire": "atheist|disbelieves",
    "atheist_internet": "internet|argues on",
    "atheist_time": "time|erodes belief",
    "atheist_cow": "atheist|eats",

    // --- BITCOIN ---
    "bitcoin_alien": "alien|doesn't accept",
    "bitcoin_sponge": "sponge|cleans",
    "bitcoin_dragon": "dragon|hoards gold",
    "bitcoin_gun": "gun|steals wallet",
    "bitcoin_wall": "wall|blocks wifi",
    "bitcoin_computer": "computer|mines",
    "bitcoin_money": "bitcoin|replaces",
    "bitcoin_camera": "camera|screenshots",
    "bitcoin_sun": "sun|fries grid",
    "bitcoin_vampire": "vampire|prefers blood",
    "bitcoin_internet": "internet|hosts",
    "bitcoin_time": "time|crashes market",
    "bitcoin_cow": "cow|doesn't care",

    // --- ALIEN ---
    "alien_sponge": "alien|probes",
    "alien_dragon": "alien|abducts",
    "alien_gun": "alien|forcefields",
    "alien_wall": "alien|teleports",
    "alien_computer": "alien|hacks",
    "alien_money": "alien|burns",
    "alien_camera": "camera|is blurry",
    "alien_sun": "alien|orbits",
    "alien_vampire": "alien|has toxic blood",
    "alien_internet": "internet|leaks photos",
    "alien_time": "alien|travels",
    "alien_cow": "alien|steals",

    // --- SPONGE ---
    "sponge_dragon": "dragon|burns",
    "sponge_gun": "gun|shoots",
    "sponge_wall": "wall|scrapes",
    "sponge_computer": "sponge|cleans screen",
    "sponge_money": "money|buys",
    "sponge_camera": "camera|films",
    "sponge_sun": "sun|dries",
    "sponge_vampire": "vampire|tears",
    "sponge_internet": "internet|absorbs info",
    "sponge_time": "time|rots",
    "sponge_cow": "cow|eats",

    // --- DRAGON ---
    "dragon_gun": "dragon|melts",
    "dragon_wall": "dragon|flies over",
    "dragon_computer": "dragon|hoards",
    "dragon_money": "dragon|hoards",
    "dragon_camera": "dragon|poses",
    "dragon_sun": "sun|is hotter",
    "dragon_vampire": "dragon|burns",
    "dragon_internet": "internet|makes viral",
    "dragon_time": "time|fossilizes",
    "dragon_cow": "dragon|snacks",

    // --- GUN ---
    "gun_wall": "wall|stops bullet",
    "gun_computer": "gun|shoots screen",
    "gun_money": "money|buys",
    "gun_camera": "gun|shoots lens",
    "gun_sun": "sun|melts",
    "gun_vampire": "vampire|dodges",
    "gun_internet": "internet|sells",
    "gun_time": "time|rusts",
    "gun_cow": "gun|shoots",

    // --- WALL ---
    "wall_computer": "wall|blocks wifi",
    "wall_money": "money|buys",
    "wall_camera": "wall|blocks view",
    "wall_sun": "wall|cracks",
    "wall_vampire": "vampire|climbs",
    "wall_internet": "internet|penetrates",
    "wall_time": "time|crumbles",
    "wall_cow": "cow|jumps over (moon)",

    // --- COMPUTER ---
    "computer_money": "money|buys",
    "computer_camera": "computer|stores photos",
    "computer_sun": "sun|overheats",
    "computer_vampire": "computer|no reflection",
    "computer_internet": "internet|connects",
    "computer_time": "time|obsoletes",
    "computer_cow": "cow|steps on",

    // --- MONEY ---
    "money_camera": "money|buys",
    "money_sun": "money|burns",
    "money_vampire": "money|buys castle",
    "money_internet": "internet|steals",
    "money_time": "time|is money",
    "money_cow": "money|buys",

    // --- CAMERA ---
    "camera_sun": "sun|blinds",
    "camera_vampire": "vampire|no reflection",
    "camera_internet": "internet|uploads",
    "camera_time": "camera|freezes",
    "camera_cow": "camera|films",

    // --- SUN ---
    "sun_vampire": "sun|incinerates",
    "sun_internet": "sun|solar flares",
    "sun_time": "sun|burns out",
    "sun_cow": "cow|sunburns",

    // --- VAMPIRE ---
    "vampire_internet": "internet|exposes",
    "vampire_time": "vampire|is immortal",
    "vampire_cow": "vampire|drinks",

    // --- INTERNET ---
    "internet_time": "internet|wastes",
    "internet_cow": "internet|memes",

    // --- TIME ---
    "time_cow": "time|ages"
};